name: insta_extractor
description: This plugin lets you download instagram reels, igtv, posts, stories
version: 1.0.0
repository: https://github.com/TamilKannanCV-personal/insta_extractor.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  plugin:
    platforms:
      android:
        package: com.tk.insta_extractor
        pluginClass: InstaExtractorPlugin
      ios:
        pluginClass: InstaExtractorPlugin
